#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# uninstall oldstyle-files
targetfile="/Library/StartupItems/KeyRemap4MacBook/KeyRemap4MacBook.kext/Contents/Info.plist"
if [ -f "$targetfile" ]; then
    if grep -q org.pqrs "$targetfile"; then
        # save configuration before remove.
        /Applications/KeyRemap4MacBook/scripts/save.sh

        /Library/StartupItems/KeyRemap4MacBook/KeyRemap4MacBook stop
        rm -rf "/Library/StartupItems/KeyRemap4MacBook/"
    fi
fi

# move oldstyle config
if [ -f "/Applications/KeyRemap4MacBook/scripts/sysctl.sh" ]; then
    mv -f "/Applications/KeyRemap4MacBook/scripts/sysctl.sh" "/Library/org.pqrs/KeyRemap4MacBook/scripts"
fi

# uninstall obsolute files
rm -f "/Library/LaunchDaemons/org.pqrs.KeyRemap4MacBook.autosave.plist"
rm -f "/Library/LaunchAgents/org.pqrs.KeyRemap4MacBook.server.plist"
rm -rf "/Applications/KeyRemap4MacBook"

startup="/Library/org.pqrs/KeyRemap4MacBook/scripts/startup.sh"
[ -f "$startup" ] && "$startup" quickstart

launchctl load /Library/LaunchDaemons/org.pqrs.KeyRemap4MacBook.server.plist

exit 0
