all:
	$(MAKE) -C launchd
	$(MAKE) -C prefpane
	$(MAKE) -C statusbar
	$(MAKE) -C uninstaller

clean:
	$(MAKE) -C launchd clean
	$(MAKE) -C prefpane clean
	$(MAKE) -C statusbar clean
	$(MAKE) -C uninstaller clean
