all:
	$(MAKE) -C AXNotifier
	$(MAKE) -C EventViewer
	$(MAKE) -C cli
	$(MAKE) -C multitouchextension
	$(MAKE) -C post-hid-event
	$(MAKE) -C preferences
	$(MAKE) -C read-symbolichotkeys
	$(MAKE) -C updater
	$(MAKE) -C warp-mouse-cursor-position

clean:
	$(MAKE) -C AXNotifier clean
	$(MAKE) -C EventViewer clean
	$(MAKE) -C cli clean
	$(MAKE) -C multitouchextension clean
	$(MAKE) -C post-hid-event clean
	$(MAKE) -C preferences clean
	$(MAKE) -C read-symbolichotkeys clean
	$(MAKE) -C updater clean
	$(MAKE) -C warp-mouse-cursor-position clean
