CXXFLAGS = -I../../ -Wall -Werror -O2
LDFLAGS =-F$(HOME)/Library/Frameworks -framework gtest \
	-L$(HOME)/Library/Frameworks/gtest.Framework/Resources \
	-lgtest_main

SOURCES=$(wildcard *.cpp)
OBJECTS=$(patsubst %.cpp,%.o,$(SOURCES))
