CXXFLAGS = \
    -I../../Pods/Headers/GoogleTest \
    -I/usr/local/include \
    -Wall -Werror \
    -O2 \
    -std=c++11

LDFLAGS = \
	-L../../Pods/build/Release/ \
    -lPods \
    -lPods-GoogleTest

SOURCES=$(wildcard *.cpp)
OBJECTS=$(patsubst %.cpp,%.o,$(SOURCES))
