#ifndef BRIDGE_H
#define BRIDGE_H

enum {
  BRIDGE_DATATYPE_NONE,
  BRIDGE_DATATYPE_KEYCODE,
  BRIDGE_DATATYPE_MODIFIERFLAG,
  BRIDGE_DATATYPE_FLAGS,
  BRIDGE_DATATYPE_CONSUMERKEYCODE,
  BRIDGE_DATATYPE_POINTINGBUTTON,
  BRIDGE_DATATYPE_OPTION,

  BRIDGE_REMAPTYPE_NONE,
  BRIDGE_REMAPTYPE_KEYTOKEY,
  BRIDGE_REMAPTYPE_KEYTOCONSUMER,
  BRIDGE_REMAPTYPE_KEYTOPOINTINGBUTTON,
  BRIDGE_REMAPTYPE_CONSUMERTOCONSUMER,
  BRIDGE_REMAPTYPE_CONSUMERTOKEY,
  BRIDGE_REMAPTYPE_DOUBLEPRESSMODIFIER,
  BRIDGE_REMAPTYPE_DROPKEYAFTERREMAP,
  BRIDGE_REMAPTYPE_HOLDINGKEYTOKEY,
  BRIDGE_REMAPTYPE_IGNOREMULTIPLESAMEKEYPRESS,
  BRIDGE_REMAPTYPE_KEYOVERLAIDMODIFIER,
  BRIDGE_REMAPTYPE_POINTINGBUTTONTOKEY,
  BRIDGE_REMAPTYPE_POINTINGBUTTONTOPOINTINGBUTTON,
  BRIDGE_REMAPTYPE_POINTINGRELATIVETOSCROLL,
  BRIDGE_REMAPTYPE_SIMULTANEOUSKEYPRESSES,

  BRIDGE_FILTERTYPE_NONE,
  BRIDGE_FILTERTYPE_APPLICATION_NOT,
  BRIDGE_FILTERTYPE_APPLICATION_ONLY,
  BRIDGE_FILTERTYPE_CONFIG_NOT,
  BRIDGE_FILTERTYPE_CONFIG_ONLY,
  BRIDGE_FILTERTYPE_DEVICE_NOT,
  BRIDGE_FILTERTYPE_DEVICE_ONLY,
  BRIDGE_FILTERTYPE_INPUTMODE_NOT,
  BRIDGE_FILTERTYPE_INPUTMODE_ONLY,
  BRIDGE_FILTERTYPE_INPUTMODEDETAIL_NOT,
  BRIDGE_FILTERTYPE_INPUTMODEDETAIL_ONLY,
};

#endif
