// -*- Mode: objc; Coding: utf-8; indent-tabs-mode: nil; -*-

#define kIsStatusBarEnabled @"isStatusbarEnable"
#define kIsShowSettingNameInStatusBar @"isShowSettingNameInStatusBar"
#define kConfigListSelectedIndex @"selectedIndex"
#define kCheckForUpdates @"isCheckUpdate"
#define kIsStatusWindowEnabled @"isStatusWindowEnabled"
#define kIsStatusWindowShowCapsLock @"isStatusWindowShowCapsLock"
#define kIsStatusWindowShowStickyModifier @"isStatusWindowShowStickyModifier"
#define kIsStatusWindowShowPointingButtonLock @"isStatusWindowShowPointingButtonLock"
#define kStatusWindowType @"statusWindowType"
#define kStatusWindowTheme @"statusWindowTheme"
#define kStatusWindowOpacity @"statusWindowOpacity"
#define kStatusWindowFontSize @"statusWindowFontSize"
#define kStatusWindowPosition @"statusWindowPosition"
#define kIsAXNotifierEnabled @"kIsAXNotifierEnabled"
#define kAXNotifierDisabledInJavaApps @"kAXNotifierDisabledInJavaApps"
#define kAXNotifierDisabledInQtApps @"kAXNotifierDisabledInQtApps"
#define kAXNotifierDisabledInPreview @"kAXNotifierDisabledInPreview"
#define kAXNotifierDisabledInMicrosoftOffice @"kAXNotifierDisabledInMicrosoftOffice"
#define kUsePreparedSettings @"kUsePreparedSettings"
#define kIsMigratedIsOverwriteKeyRepeat @"kIsMigratedOverwriteKeyRepeat"
#define kIsOverwriteKeyRepeat @"kIsOverwriteKeyRepeat"
#define kShowIconInDock @"kShowIconInDock"

#define kKarabinerPreferencesWidth @"kKarabinerPreferencesWidth"
#define kKarabinerPreferencesHeight @"kKarabinerPreferencesHeight"
#define kKarabinerPreferencesCheckboxFont @"kKarabinerPreferencesCheckboxFont"
