all:
	$(MAKE) -C DumpInputModeToConsole
	$(MAKE) -C KeyDump
	$(MAKE) -C GetActiveApplicationName
	$(MAKE) -C ThreeFingerRelativeToScroll

clean:
	$(MAKE) -C DumpInputModeToConsole clean
	$(MAKE) -C KeyDump clean
	$(MAKE) -C GetActiveApplicationName clean
	$(MAKE) -C ThreeFingerRelativeToScroll clean
