all:
	$(MAKE) -C DumpInputModeToConsole
	$(MAKE) -C KeyDump
	$(MAKE) -C getActiveApplication

clean:
	$(MAKE) -C DumpInputModeToConsole clean
	$(MAKE) -C KeyDump clean
	$(MAKE) -C getActiveApplication clean
