all:
	@echo "type 'make install'"

install:
	sudo cp -r *.xml include /Applications/KeyRemap4MacBook.app/Contents/Resources
	sudo /Applications/KeyRemap4MacBook.app/Contents/Library/extra/setpermissions.sh /Applications/KeyRemap4MacBook.app/Contents/Resources
