all:
	rm -rf output
	mkdir output
	./keytokey.rb 2 5 >> output/include.keytokey.hpp
	./keytokey.rb 3 5 >> output/include.keytokey.hpp
	./keytokey.rb 4 5 >> output/include.keytokey.hpp
	./keytokey.rb 5 5 >> output/include.keytokey.hpp

