all:
	rm -rf output
	mkdir output
	./keytokey.rb 2 5 >> output/include.keytokey.hpp
	./keytokey.rb 3 5 >> output/include.keytokey.hpp
	./keytokey.rb 4 5 >> output/include.keytokey.hpp
	./keytokey.rb 5 5 >> output/include.keytokey.hpp

	./keyoverlaidmodifier.rb 2 6 >> output/include.keyoverlaidmodifier.hpp
	./keyoverlaidmodifier.rb 3 6 >> output/include.keyoverlaidmodifier.hpp
	./keyoverlaidmodifier.rb 4 6 >> output/include.keyoverlaidmodifier.hpp
	./keyoverlaidmodifier.rb 5 6 >> output/include.keyoverlaidmodifier.hpp
	./keyoverlaidmodifier.rb 6 6 >> output/include.keyoverlaidmodifier.hpp

	./keyeventinputqueue.rb 1 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 2 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 3 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 4 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 5 5 >> output/include.keyeventinputqueue.hpp
