all:
	rm -rf output
	mkdir output
	./keytokey.rb 2 5 >> output/include.keytokey.hpp
	./keytokey.rb 3 5 >> output/include.keytokey.hpp
	./keytokey.rb 4 5 >> output/include.keytokey.hpp
	./keytokey.rb 5 5 >> output/include.keytokey.hpp

	./keyeventinputqueue.rb 1 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 2 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 3 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 4 5 >> output/include.keyeventinputqueue.hpp
	./keyeventinputqueue.rb 5 5 >> output/include.keyeventinputqueue.hpp

	./pointingbuttontokey.rb 1 5 >> output/include.pointingbuttontokey.hpp
	./pointingbuttontokey.rb 2 5 >> output/include.pointingbuttontokey.hpp
	./pointingbuttontokey.rb 3 5 >> output/include.pointingbuttontokey.hpp
	./pointingbuttontokey.rb 4 5 >> output/include.pointingbuttontokey.hpp
	./pointingbuttontokey.rb 5 5 >> output/include.pointingbuttontokey.hpp
