all:
	$(MAKE) -C lib
	$(MAKE) -C bin
	$(MAKE) -C core
	$(MAKE) -C util
	$(MAKE) -C vendor

clean:
	$(MAKE) -C lib clean
	$(MAKE) -C bin clean
	$(MAKE) -C core clean
	$(MAKE) -C util clean
	$(MAKE) -C vendor clean
