#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    /Applications/KeyRemap4MacBook.app \
    ; do
    echo "set file permissions: $f"
    sh /Applications/KeyRemap4MacBook.app/Contents/Library/extra/setpermissions.sh "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
# relaunch KeyRemap4MacBook.app

/Applications/KeyRemap4MacBook.app/Contents/Applications/KeyRemap4MacBook_cli.app/Contents/MacOS/KeyRemap4MacBook_cli \
    relaunch

# ------------------------------------------------------------
exit 0
