#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    /Applications/Karabiner.app \
    ; do
    echo "set file permissions: $f"
    sh /Applications/Karabiner.app/Contents/Library/extra/setpermissions.sh "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
# relaunch KeyRemap4MacBook.app

/Applications/Karabiner.app/Contents/Library/bin/karabiner \
    relaunch

# ------------------------------------------------------------
exit 0
