#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin; export PATH

# ------------------------------------------------------------
# set file permissions
for f in \
    /Library/LaunchAgents/org.pqrs.KeyRemap4MacBook.server.plist \
    /Applications/KeyRemap4MacBook.app \
    ; do
    echo "set file permissions: $f"
    sh /Applications/KeyRemap4MacBook.app/Contents/Library/extra/setpermissions.sh "$f"
    chown -Rh root:wheel "$f"
done

# ------------------------------------------------------------
exit 0
